### ISSUE TITLE
Root index.md doesn't show title

### ISSUE THREAD

**Issue by baobab-it** [testingisdocumenting/znai#1008]
Main page `toc/index.md` doesn't show title.

```
---
title: Title page
---
```

**Comment by MykolaGolubyev** [comment]
Interesting. Yeah index is probably not supported with titles. Will think how to add it. Thanks for reporting. 

I also noticed that a lot of our internal docs people don’t know what to put on index page and they remove it instead.

**Comment by MykolaGolubyev** [comment]
this was releases as 1.61
