### ISSUE TITLE
[Feature Extension] Extend filtering capabilities for tables

### ISSUE THREAD

**Issue by preetTS** [testingisdocumenting/znai#1011]
The [Arrange and Filter](https://testingisdocumenting.org/znai/layout/tables#arrange-and-filter) feature is pretty useful for tables.

Can it be extended so that it supports query-based filters?

For example: `:include-table: table.csv {columns: ["Item", "Description", "Price"] where:["Item=pen"]}`
This would only show rows from table.csv where the value of "Item" is "pen".

A further extension could be wildcards and aggregation, but a simple equality based filter (as above) would be great too.

**Comment by MykolaGolubyev** [comment]
Hi @preetTS, thanks for the request, appreciate it. 
Need to think on implications of custom expressions. 
will something like simple contains: subtext work?

Do you by any chance work at Two Sigma?

**Comment by preetTS** [comment]
@MykolaGolubyev - thanks for following up.

`contains: <subtext>` should suffice; the equality based comparison is implicit in it and this would work just as well.

Yes, I do work at Two Sigma.

**Comment by MykolaGolubyev** [comment]
To double check, contains: “pen”, will match rows with “penthouse”. Will that still be good?

**Comment by preetTS** [comment]
Yep, that should still be good :)

**Comment by MykolaGolubyev** [comment]
@preetTS @byc1234 will need to make it available internally. Changes are in main branch.

**Comment by MykolaGolubyev** [comment]
wanted to followup and check if there is any help required
@preetTS @byc1234

**Comment by preetTS** [comment]
We should be set now. Thanks, @MykolaGolubyev!
