### ISSUE TITLE
Use bullets in table

### ISSUE THREAD

**Issue by preetTS** [testingisdocumenting/znai#1013]
Hi again, @MykolaGolubyev 

How do I use bullets within a table cell? I tried markup `* point1 * point2`, but it shows up wonky (can't seem to attach a picture here). This happens both with Github flavored and csv tables.

Thanks!

**Comment by MykolaGolubyev** [comment]
Hello!
Use quotes to wrap multiple lines
`````
Account, Price, Description
#12BGD3, 100, "multi line markdown with
* bullet point
* list
"
#12BGD3, 150, "and some code snippet
```java
class HelloWorld {
}
```
"
`````

**Comment by MykolaGolubyev** [comment]
Let me know if you want to a brainstorm on how to better organize your docs, and what plugins may be good to use
