### ISSUE TITLE
Nesting cards causes the nested images to not be included

### ISSUE THREAD

**Issue by MrLar** [testingisdocumenting/znai#1024]
When nesting a card as such:

`````
````card [path] {title: "[title]"}

```card [path2] {title: "[title2]"}
```

````
`````
The secondary (path2) is not included in the building process (unless its already included from somewhere else), neither for preview nor for gen. This causes the card to simply fallback to the alt attribute.

I know this probably isn't exactly the intended use cause for cards and would honestly understand if this can't/won't be fixed.

Noteworthy is however that the image (and entire card) works properly if the image gets included from somewhere else, it just breaks if it's the only source of the image.

In preview this can behave rather dodgy, as in sometimes the image works - sometimes it doesn't. However for actually genning the page you can verify that the file will be missing from the output.

An example use case:
![](https://mrlar.dev/i/IwRB1BJRpF3ZiGoG1KRP9.png)

**Comment by MykolaGolubyev** [comment]
Oh interesting usecase! Even though not planned I believe it should be fixed to work as expected. Going to take a look later today. Thank you for the report!

**Comment by MykolaGolubyev** [comment]
turned out it is not just for nested card, but for any image referenced inside a card content.
I can push a patch if you plan to use the fix soon.

**Comment by MrLar** [comment]
It's not exactly urgent for us, so it's fine if the fix isn't immediate

**Comment by Haxiz** [comment]
Hey, its been a while!
If possible when the patch is out could you mention either of us?

That way we'll be able to make the new build and publish the new pages we have. Once we have that we'll be basically done with the project (aside from updates of course)

**Comment by MykolaGolubyev** [comment]
Hello! Of course. 
I am eager to see what your docs look like. May push a patch tonight as I will be OOO for some time.

**Comment by MykolaGolubyev** [comment]
@Haxiz @MrLar 1.61.2 is released

**Comment by Haxiz** [comment]
@MykolaGolubyev its up!
https://www.mantaro.site/mantaro-wiki/

**Comment by MykolaGolubyev** [comment]
I don’t see cards :( maybe cache. Will try later.

**Comment by MrLar** [comment]
We only really use cards in <https://www.mantaro.site/mantaro-wiki/currency/items>, <https://www.mantaro.site/mantaro-wiki/currency/badges> and some in 102 to 104 of currency.

**Comment by MykolaGolubyev** [comment]
Nice! Thanks for sharing. 
congrats on the push. Docs are very detailed and very well structured. 

One thing I noticed is some tables here are more readable on mobile then the others 
https://www.mantaro.site/mantaro-wiki/basics/server-configuration

**Comment by Haxiz** [comment]
> One thing I noticed is some tables here are more readable on mobile then the others
https://www.mantaro.site/mantaro-wiki/basics/server-configuration

Yeah that page we had to leave mostly as it was before as there is a planned update that will overhaul that section. So we didn't think it was worth remaking the page if we would have to remake everything later down the road.
