### ISSUE TITLE
document how to deploy znai in a container

### ISSUE THREAD

**Issue by antoinell** [testingisdocumenting/znai#1061]
I am trying to figure out how to create a docker image with a server to view znai documentation and the documentation itself. 

I figured out that using the `znai-dist` artifact could be a nice way.
So I am trying to use `znai --serve` . What is supposed to be the workflow ?
I downloaded znai on my Mac.I ran `~/Downloads/dist/znai --new` to have some content to serve.
then `~/Downloads/dist/znai --source znai --doc-id my-znai --deploy ./znai-deploy --serve`
A server starts but the web page does not include something useful.
On http://localhost:3333 The server serves a page saying "Company guides" with a text box saying "Find documentation".
This command
`~/Downloads/dist/znai --source znai --preview` produces something useful under http://localhost:3333/preview/ .

**Comment by MykolaGolubyev** [comment]
Hello @antoinell,
Happy New Year!

to host a single documentation any HTTP static server should work. Or if you already have a static files host server, you should be able to copy generated HTML files over there. Make sure doc-id matches the dir name under server.

Znai --serve is to host a Hub of documentations company wide and is not documented at the moment. If it is the Hub you are looking for, I can help you over a call.

**Comment by antoinell** [comment]
Thanks a lot @MykolaGolubyev . I am using busybox now as a HTTP static server.
