### ISSUE TITLE
Change include-json's include to not "zoom in" to the included object when there is only a single include path.

### ISSUE THREAD

**Issue by motlin** [testingisdocumenting/znai#1078]
I use include-json's include feature in [my docs](https://liftwizard.io/docs/database/named-data-source/).

I show a json object, filtered down to a single top-level property. Here's there real example:

```json
{
  "liquibase": {
    "enabled": true,
    "dataSourceMigrations": [
      {
        "dataSourceName": "h2-tcp",
        "migrationFileName": "migrations.xml",
        "migrationFileLocation": "classpath",
        "contexts": []
      }
    ],
    "dryRun": false
  }
}
```

I found that when I include a single path `include: "$['liquibase']"`, then the root object is now the inner object, I have to change my paths to be relative to the inner object, and the output renders like this:

```json
{
  "enabled": true,
  "dataSourceMigrations": [
    {
      "dataSourceName": "h2-tcp",
      "migrationFileName": "migrations.xml",
      "migrationFileLocation": "classpath",
      "contexts": []
    }
  ],
  "dryRun": false
}
```

Since I want it to render the first way, I experimented and came up with a workaround. I can include a second property, which is fake/absent, and Znai will render my docs the way I like.

```
:include-json: test-example.json5 {
title: "example.json5",
include: "$['absent', 'liquibase']",
}
```

I'd like to have a way to filter the json properties without changing the root object. One recommendation would be to have separate directives for choosing a root object and filtering properties. In my case, I'd leave it absent or set to the root. Something like this:

```
:include-json: test-example.json5 {
title: "example.json5",
root: "$",
include: "$['liquibase']",
}
```

**Comment by MykolaGolubyev** [comment]
@motlin I can't find a proper way to do it with the library Znai uses (https://github.com/json-path/JsonPath)
Workaround you can try is using `encloseInObject`: https://testingisdocumenting.org/znai/snippets/json#enclose-in-object
