### ISSUE TITLE
API spec rendering - put default last

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/znai#108]
In API spec, responses are defined for specific status codes but it is also possible to add a "default" response.  I believe this is really more of a "else" in that it indicates the response if it's not one of the explicit status codes.

Therefore, I think the default should be displayed as the last entry in MDoc's responses rendering, first the explicit codes then the implicit one.

**Comment by MykolaGolubyev** [comment]
Closing for now. Feel free to reopen if new openapi3 render is not working for you
