### ISSUE TITLE
Links in cards not working in preview mode

### ISSUE THREAD

**Issue by jenspfahl-tgtg** [testingisdocumenting/znai#1114]
[Links in cards](https://testingisdocumenting.org/znai/visuals/cards#links) are not working for me in preview mode.

I have a toc file like this:
```
SSO-Integration
    introduction
    onboarding
```

I have a card in the landing page (index.md) like this
```

 ```````columns
 left:
   somethingsomething
 
 right:
  ```card img.png {title: "Single Sign-On", imageHeight: 180}
  somethingsomething
  [Learn More](SSO-Integration/introduction)

```

In preview mode the link points to `/preview` but not to the actual page. Navigation links work fine so the structure is corect.

version 1.61.2 (Homebrew)

**Comment by jenspfahl-tgtg** [comment]
Thanks for the fast reaction 👍

**Comment by MykolaGolubyev** [comment]
of course! Any chance you can share your use case of Znai here? https://github.com/testingisdocumenting/znai/discussions/824
