### ISSUE TITLE
Consider robots.txt files to be published automatically

### ISSUE THREAD

**Issue by jenspfahl-tgtg** [testingisdocumenting/znai#1117]
I want to publish a robots.txt file when generating the site (ideally also in preview mode). Just placing the file next to the meta.json doesn't work. It would be best that Znai detects and takes this file automatically.

**Comment by MykolaGolubyev** [comment]
do you plan to use sitemaps.xml files? I have never created robots.txt and just checked an example. Some of them refer to other xml files. I assume you may want to upload them as well?

**Comment by jenspfahl-tgtg** [comment]
I think both is needed. Depending on the requirements sometimes a robots.txt is sufficient but somethimes both is needed. So being flexible here would be great.

**Comment by MykolaGolubyev** [comment]
@jenspfahl-tgtg let me know if you have anything else you would like to request. I am going to deploy new version today/tomorrow
