### ISSUE TITLE
GPL licensed version of plantuml breaking corporate rules

### ISSUE THREAD

**Issue by antoinell** [testingisdocumenting/znai#1142]
The dependency of the znai-maven-plugin to plantuml is breaking corporate rules to ban GPL licensed artifacts. 
Fortunately there is a plantuml-bsd artifact. Can we check whether it can replace the current plantuml dependency for znai and create a new release?

**Comment by MykolaGolubyev** [comment]
Ah, this makes a lot of sense. Thanks @antoinell. Will take a stab at it.

**Comment by antoinell** [comment]
Thanks for the fast turnaround ! Looking forward to the next release !

**Comment by MykolaGolubyev** [comment]
1.65 was pushed to maven central

**Comment by antoinell** [comment]
Great news @MykolaGolubyev , thanks a lot.
