### ISSUE TITLE
Interest in Enterprise Server

### ISSUE THREAD

**Issue by sentara-axpalat** [testingisdocumenting/znai#1201]
We're interested in running a local enterprise server instance of Znai.  Opening issue for that discussion.

**Comment by MykolaGolubyev** [comment]
What is your team familiarity with Java and shell?
Will your documentation need authorization? Or is it available internally for everyone?

**Comment by sentara-axpalat** [comment]
Hey Mykola,

I can’t be sure of that as I’m new to the organization, but I have at least 30 years with both.  The organization has some Java.  Would there be alternative to the shell part like from a git repo or other source?
We might need authorization.  We’re oauth/oidc if that’s supported?

I’ve played with Znai for a couple of years now, and love the project and have used it locally do document a couple of projects.  Now I’m evaluating as possible tool for our Solutions Architecture group to use.

Thanks,

Anil

On Apr 23, 2024, at 7:20 AM, Mykola Golubyev ***@***.***> wrote:

Notice: This email originated outside the Sentara Health network. Beware of links and attachments. Report suspicious emails with the Report Phishing button.



What is your team familiarity with Java and shell?
Will your documentation need authorization? Or is it available internally for everyone?

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1Yf_hxAw2y-qpX04ZCyWd5_2x-g3cyCiLacBjsRMw7JNiV1ekc3oApA-Hz4hVgcJoCsljzbBBU1-DxS3g_0dPO8DgQTDJBeti5gzGa5xN4YMUlOjWcz-jZKrTfKLTBGEoiV6a2PiDRlrM-QEzdqzS6KH_KlZtt04p-NmrP-wsguqUKhF2XxPvoWa9FWKhtpIa1HdL7zBGO9GitDB-OXlLn9GU-wyS38jgyJFcdEaPDIWEqyw1VMoouxPyazwe89BtM1JxaRjkWzqEVzr6o4xvlqsiDkQ8x-wNkiyLT_dLdBPhLhB4wpTQCf7LfZfXEjHc/https%3A%2F%2Fgithub.com%2Ftestingisdocumenting%2Fznai%2Fissues%2F1201%23issuecomment-2072040878>, or unsubscribe<https://secure-web.cisco.com/1_EybwikjLesPlXhgblmJMdG-D37Rf1tmU6Q4Z7dl7Rp6g6Aj8gesRrS_sVzULiMmSW1Bz9HBuKB3PoaaEj1ITQQYLjfKAXfkLBo8U6NSgTZIO-vD5bk45Ca153ZOVp3ZfSdg8yi_Q_y9FSNA1t9-LpC8hfpsIkfCQ3VnDTCkB7JY12GQ8vf6Bwf9kRPNx4A3dBkxO_AljxQI5q7ZQuclA-JLOgVKAzDvzL2wCwNnQVWApfAugEdiRfUy8GPFVWluSl9Tto0Zs8KeguvwYFupjp1SLysU1Fr1AuCDErbwnY4PmsYuUKQQquTd3TKeHx0H/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FBFXW5P4LPNSUOT6UU5TAWKDY6Y7XXAVCNFSM6AAAAABGUBYNYKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANZSGA2DAOBXHA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

Disclaimer:


This electronic message and its contents and attachments contain information from Sentara Health and is confidential or otherwise protected from disclosure. The information is intended to be for the addressee only.

If you are not the addressee, any disclosure, copy, distribution or use of the contents of this message is prohibited. If you have received this electronic message in error, please notify us immediately and destroy the original message and all copies.

**Comment by MykolaGolubyev** [comment]
This is perfect! Also glad to hear you have been using znai for quite some time. Do you mind sharing the use cases here: https://github.com/testingisdocumenting/znai/discussions/824

As a starting point please take a look at this end to end test for znai hub: znai-tests/src/test/groovy/scenarios/hub.groovy

There are extension points and different ways how docs could be registered/discovered. Those implementations are specific to a company decision (e.g. znai-enterprise/src/main/java/org/testingisdocumenting/znai/enterprise/landing/LandingDocEntriesProvider.java and files in the same module)

There is also a chance that you may not need a znai hub and could get away with any server that knows how to host static content. However I would like to use this opportunity to flash out APIs and create docs if you will find it useful to pursue Hub thing.

**Comment by MykolaGolubyev** [comment]
@sentara-axpalat did you have a chance to look at it?

**Comment by MykolaGolubyev** [comment]
@sentara-axpalat bumping
