### ISSUE TITLE
Landing page is not shown

### ISSUE THREAD

**Issue by jenspfahl-tgtg** [testingisdocumenting/znai#1205]
Hi! 
I worked with version 1.64 for a while and with this version, the landing page (index.md in the root) was rendered and displayed as expected. It worked for preview and release mode.
Then I upgraded to 1.68 and suddenly the landing page is not shown for preview and release anymore, but the site is immediatelly forwarded to the first page defined in the toc. 
This is not what i expected. I still want to present a nice landing page. Is this a bug or is there a new feature setting to enable this again?
Thanks for looking into this.

**Comment by MykolaGolubyev** [comment]
I believe 1.69 has the fix. It should be available in Maven central now. 
If you use brew, let me know.

**Comment by MykolaGolubyev** [comment]
Updated brew. Could you please try again?

**Comment by jenspfahl-tgtg** [comment]
Works now, thanks!
