### ISSUE TITLE
meta.json Index Link is Broken

### ISSUE THREAD

**Issue by jamesjreynolds** [testingisdocumenting/znai#1208]
**Affects**: 1.68

In 1.67, the upper left corner of the rendered Znai site contains a link to the index.html page for the generated site.  It takes its linked text from the "title" field in the meta.json file.

In 1.68, the link take the user to the first page under the first directory in the TOC file.  It seems that the index page is unreachable.

Thanks for a great tool!

**Comment by MykolaGolubyev** [comment]
try 1.69
Thanks for the nice words

If you have time please write how you use znai here: https://github.com/testingisdocumenting/znai/discussions/824

A star on this project from you and your friends will also help!

**Comment by MykolaGolubyev** [comment]
@jamesjreynolds does it work for you?

**Comment by jamesjreynolds** [comment]
@MykolaGolubyev 
Please forgive the late reply.  It is working for me.  Thanks so much!
