### ISSUE TITLE
UI Customization of the Generated Site

### ISSUE THREAD

**Issue by TheSilverNimbus** [testingisdocumenting/znai#1214]
I've recently started using Znai for my own open source libraries and I was trying to find any resources or references in the official Znai guide on how to customize the look of the final generated site.

I just wanted to make some minor changes to the site, by way of the typefaces (and their sizes) and the colors of some of the elements on the page. Is it possible to make these changes?

**Comment by TheSilverNimbus** [comment]
Never mind! I found them in the `target` build folder.

**Comment by MykolaGolubyev** [comment]
@TheSilverNimbus sorry for the delay. There is a supported way to provide style overrides.
You need to create style.css file in the root (where toc file is). 
Feel free to override any css vars there. anything with znai- prefix is safe to override. The rest could be a subject to change.

**Comment by TheSilverNimbus** [comment]
Awesome. Thank you so much for the response! This was incredibly helpful!
