### ISSUE TITLE
Inline LaTeX formatting

### ISSUE THREAD

**Issue by hjstein** [testingisdocumenting/znai#1225]
### Discussed in https://github.com/testingisdocumenting/znai/discussions/1223

<div type='discussions-op-text'>

<sup>Originally posted by **hjstein** August  5, 2024</sup>
When I do something like:
```
Consider the function `:latex: {src: "f(x) = x^2"}`.
```
it renders with extra spaces before and after the LaTeX.  Is there any way to eliminate that excess space?

Thanks.
</div>

**Comment by MykolaGolubyev** [comment]
Before I release a version with the fix, please create a file `style.css` next to `toc` file and put this in there:
```
span.latex {
    margin-left: 0;
    margin-right: 0;
}
```
Note that after the release the "latex" name for css will become "znai-latex". And you won't need the file above or at least the snippet above in that file.

**Comment by MykolaGolubyev** [comment]
@hjstein please let me know if the snippet above works for you
