### ISSUE TITLE
Page watching and notification emails

### ISSUE THREAD

**Issue by mattmetlis** [testingisdocumenting/znai#261]
It would be nice for a user to be able to watch a page, or perhaps part of a page, and receive an email notification when a change is made to that page. Similar to the ability to watch a page in a wiki.

**Comment by MykolaGolubyev** [comment]
@mattmetlis I like the idea. Implementation is probably only possible for on-premise deployment, i.e. not pure static hosting like on gh-pages.
Honestly at this time I don't have a good algorithm in mind to detect that there was a change deployed. There could be multiple servers running and multiple sources of docs. 

If you have any ideas, please share.

**Comment by jyeakel** [comment]
An implementation is easier to conceptualize if there is a notion of persisted, versioned releases. Something like this might be downstream from providing that capability.

**Comment by MykolaGolubyev** [comment]
@jyeakel that's a good point. But in case of a monorepo it may not be as straightforward as you most likely won't be saving each new version to a DB. However you could save the last one to DB and then compare. 
If it helps we could at some point discuss this using chat.

**Comment by mattmetlis** [comment]
Those are good points. I had not given a lot of thought to the implementation. Maybe this functionality would make more sense as part of a deployment pipeline for the docs instead of within Znai itself, since the pipeline would be capable of comparing the currently deployed version with the new version.

**Comment by MykolaGolubyev** [comment]
@jyeakel any more thoughts on this one?

**Comment by MykolaGolubyev** [comment]
@jyeakel @byc1234 as we formalizing more `znai-enterprise` module I think this can be achieved moving forward. 
We will need to introduce the concept of watchers and come up with a diff algorithm. At the minimum it can be a simple page name and page section names with changes and a link.
