### ISSUE TITLE
Create mechanism for sending exerpted document text with user comment to external endpoints

### ISSUE THREAD

**Issue by jyeakel** [testingisdocumenting/znai#292]
We plan to build an integration with Slack that will allow users to select some text in Znai documentation, and send it to a Slack channel along with some user-supplied text (comment, question, feedback, etc.). 

We expect that the specific endpoint will be configured by the documentation creator so they can decide to what communications channels they support.

In terms of the user workflow, we imagine that a contextual menu will appear when text is highlighted, presenting one or more options for endpoints. Once an endpoint is selected, a modal will present:
- The selected text
- An input box for user comment
- The destination where the message will be sent
- A confirmation button to send the message

**Comment by MykolaGolubyev** [comment]
Long standing feature. Would be nice to start putting some effort into it :)
Do you envision internal users will provide different end points or will be it managed centrally within your org?
