### ISSUE TITLE
Wild card search doesn't highlight a matching word.

### ISSUE THREAD

**Issue by byc1234** [testingisdocumenting/znai#338]
For the below snippet, I can search with `abc*` to find `abc.def.xyz.Util`, but I don't see a highlight for the matching area.

    ```java
    import abc.def.xyz.Util;

    class InternationalPriceService implements PriceService {
        private static void LongJavaInterfaceNameWithSuperFactory createMegaAbstractFactory(final ExchangeCalendarLongerThanLife calendar) {
            ...
        }
    }
    ```

**Comment by MykolaGolubyev** [comment]
Are you talking about search in the docs? I didn’t realize it supports `*`.

**Comment by byc1234** [comment]
Yes, for the example, I can't search with "abc", "def", or "xyz" to find `abc.def.xyz.Util`, but I can use a wild card as described in https://lunrjs.com/guides/searching.html.

**Comment by MykolaGolubyev** [comment]
Got it. We probably should fix the problem of lunr not splitting/tokenizing dotted code right.

**Comment by MykolaGolubyev** [comment]
Debugged a bit more - the current issue is the code snippets have tokens split in different `<span>` block. Current highlight logic only highlight within a single html node.

**Comment by MykolaGolubyev** [comment]
@byc1234 did some changes, could you please check?
