### ISSUE TITLE
Fix spacing with multiple paragraphs in list items

### ISSUE THREAD

**Issue by jyeakel** [testingisdocumenting/znai#396]
The following markdown will create undesirable line spacing:
```
* First list item's first paragraph.
    This is still part of the first paragraph.

    First list item's second paragraph

* Second list item's first paragraph
```

When rendered, the first list item's second paragraph is much closer to the second list item than the other content from the first list item. When list items have several paragraphs, we should provide more spacing between the last paragraph and the following list item.

**Comment by MykolaGolubyev** [comment]
After PR is merged it will look like:

![Screen Shot 2020-04-18 at 9 45 20 PM](https://user-
images.githubusercontent.com/11657860/79677321-fce6af00-81bd-11ea-92f5-375349317338.png)

Note spacing is even now. Did you mean to make spacing even bigger? I checked how commonmark.org renders this case and they seem to use even spacing as well.

**Comment by jyeakel** [comment]
Our internal user suggested more space between the second paragraph and new list item than between the two paragraphs of the first list item, but if this is the commonmark way, I think it’s good to go that way.

**Comment by MykolaGolubyev** [comment]
To clarify, it is the way it is rendered on commonmark.org site. Not sure specs are dictating how it should be rendered though.
