### ISSUE TITLE
Don't default to new tab for links in landing page

### ISSUE THREAD

**Issue by jyeakel** [testingisdocumenting/znai#399]
Currently, if some documentation link is clicked from a Znai landing page, the documentation opens up in a new tab. As this landing page is meant to function as a portal to documentation, it doesn't seem clear that this is the proper default behavior.

I suggest that we revert to standard link behavior, and simply load the linked documentation in the current tab.

**Comment by MykolaGolubyev** [comment]
Do you want to take a stub at it? I can guide.

**Comment by MykolaGolubyev** [comment]
Take a look at `src/screens/landing/Landing.js`
```
function Documentation({documentation}) {
    const url = documentation.url ?
        documentation.url :
        documentation.id + '/'

    return (
        <div className="znai-landing-documentation">
            <a href={url} target="_blank" rel="noopener noreferrer">
                <div className="name">{documentation.name}</div>
                <div className="description">{documentation.description}</div>
            </a>
        </div>
    )
}

**Comment by MykolaGolubyev** [comment]
@evinaik do you know if you still need this one?

**Comment by jyeakel** [comment]
Sorry for the silence on this one. This is still desired in our org.
