### ISSUE TITLE
Add defaults for all maven plugin parameters.

### ISSUE THREAD

**Issue by motlin** [testingisdocumenting/znai#403]
`sourceRoot` and `docId` are missing defaults. If they are present, then it would be possible to use the plugin from the CLI without adding any snippet to the pom.xml first. For example, it should be possible to run...

```
mvn org.testingisdocumenting.znai:znai-maven-plugin:new
```

... in a fresh submodule without editing the pom.xml.

I think decent default values would be the values that make this xml redundant:

```xml
<plugin>
    <groupId>org.testingisdocumenting.znai</groupId>
    <artifactId>znai-maven-plugin</artifactId>
    <version>1.30</version>
    <configuration>
        <docId>${project.artifactId}</docId>
        <sourceRoot>${project.basedir}/src/main/znai</sourceRoot>
    </configuration>
</plugin>
```

Which would need these changes:

```groovy
    @Parameter(defaultValue = "${project.basedir}/src/main/znai")
    private String sourceRoot
```

```groovy
    @Parameter(defaultValue = "${project.artifactId}")
    private String docId
```

Alternately, the docs make it sound like the default for sourceRoot would be "documentation"

**Comment by MykolaGolubyev** [comment]
Fixed by #409
