### ISSUE TITLE
Add ability to have code blocks with soft-wrapping.

### ISSUE THREAD

**Issue by motlin** [testingisdocumenting/znai#414]
I put console output in code blocks (triple backtick) so that it looks monospaced.

Console output can be arbitrarily wide, and it's a case where soft-wrapping makes sense.

**Comment by MykolaGolubyev** [comment]
with a fixed horizontal scrolling experience, do you still need the soft wrap option?

**Comment by motlin** [comment]
Fixed horizontal scrolling helps in a lot of cases, but there are others where I think wrapping makes sense.

https://liftwizard.io/docs/logging/logging-modules

https://liftwizard.io/docs/logging/JerseyHttpLoggingBundle

I might manually wrap these examples for clarity.
