### ISSUE TITLE
Having a user feedback.

### ISSUE THREAD

**Issue by byc1234** [testingisdocumenting/znai#446]
It might be nice to include an option for users to answer: Was this page helpful? Yes or No. If no, describe improvements you would like to see. Having this user feedback loop could help us iterate/improve docs over time

**Comment by MykolaGolubyev** [comment]
I am not up to date on latest research but I recall that those kind of buttons are rarely being used :(
Would slack Contextual integration Make more sense? I.e. user selects a portion of a text and selects ask in slack button.

**Comment by MykolaGolubyev** [comment]
@jyeakel do you have any update on the approach here?

**Comment by MykolaGolubyev** [comment]
@byc1234 is this still a use case you want to pursue?
