### ISSUE TITLE
Support for video embedding

### ISSUE THREAD

**Issue by jyeakel** [testingisdocumenting/znai#522]
Allow users to include video in their docs by supporting `iframe` embedding

**Comment by MykolaGolubyev** [comment]
Could you please elaborate on `iframe` requirement? 
Is video link going to be outside of znai deployment or inside (we most likely have limit on the uploaded zip size). 

If it is an external site that supports iframe embedding, then it probably has controls like pause/play already and we don't really need to add any custom ones. 

If on the other hand it is `.mp4` like file, we probably want some customization around it.

**Comment by jyeakel** [comment]
This request is for inclusion of a video hosted outside of the Znai deployment (e.g., including a video from YouTube in your documentation by including its embed link).
