### ISSUE TITLE
templates vs. include-markdown

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/znai#526]
Could these be joined?  Are there any behavioural differences beyond the ability to specify parameters, etc?

**Comment by MykolaGolubyev** [comment]
Good question. Checked the code and there are a few differences.
* template fence plugin (```) and inlined way of setting parameters
* include-markdown have a `firstAvailable` param for overrides in open source docs when hosted on site (e.g. different getting starting blocks)

include-markdown is like a easy to comprehend/cheap version of include-template. So I would say main difference is semantics?
