### ISSUE TITLE
Support non inotify file watching mechanism for virtualization use cases

### ISSUE THREAD

**Issue by vmpn** [testingisdocumenting/znai#542]
Host shared folders do not support inotify: https://www.virtualbox.org/ticket/10660 as a result znai preview mode does not work when run inside a VM when file is being modified on host

**Comment by MykolaGolubyev** [comment]
do you think file change via polling should fix it? Wonder if I should add an option to znai to use polling as a preview trigger

**Comment by vmpn** [comment]
Yes, I believe periodic polling would work around the cases when inotify does not work, though it won't be as efficient

**Comment by MykolaGolubyev** [comment]
closing for now as is not a wide spread use case
