### ISSUE TITLE
Support diff-highlight code blocks 

### ISSUE THREAD

**Issue by jyeakel** [testingisdocumenting/znai#577]
Znai uses prismjs for syntax highlighting, but does not currently support the diff highlight plugin that applies special highlights for added and removed lines. 

See: https://prismjs.com/plugins/diff-highlight/

Please add support for this feature in Znai's syntax highlighting.

**Comment by MykolaGolubyev** [comment]
do you also want to highlight the syntax of the actual file in addition to added/removed lines (it could be a bit trickier to integrate into znai but still possible)?

**Comment by jyeakel** [comment]
Diff highlights were the focus of the request and so I would think at least sufficient for the request, but @twosigmajab can comment on the importance of additional highlighting.
