### ISSUE TITLE
Duplicate headings don't generate unique anchor IDs

### ISSUE THREAD

**Issue by jyeakel** [testingisdocumenting/znai#579]
If I have a document `chapter-one/page-one.md` with the following content:
```
## Section Subheading 1

### Example

## Section Subheading 2

### Example
```

There is no way for me to create an anchor link to the example heading under Section Subheading 2 since a URL pointing to `chapter-one/page-one/#example` will direct the browser to the heading under Section Subheading 1.

When the same text is used for multiple anchors, Znai should make sure that the IDs are unique such that anchor links will direct to the proper section.

**Comment by MykolaGolubyev** [comment]
That makes sense. The generate id rule we had was created when we only supported level one heading and level one should be unique. Level 2 like `example` makes sense.
