### ISSUE TITLE
Znai index doesn't include subheading text

### ISSUE THREAD

**Issue by jyeakel** [testingisdocumenting/znai#589]
While first-level headings are indexed and used as the smallest unit for search results, any level subheading below that is not present in the index at all, making important subheading information invisible to search queries.

**Comment by MykolaGolubyev** [comment]
could you please add an example? I want to make sure I follow it completely.

**Comment by jyeakel** [comment]
An example (albeit somewhat confusing given the content) can be found in the [Znai docs](https://testingisdocumenting.org/znai/search-entries.xml):
```
<entry>
<url>/znai/flow/structure#sub-headings</url>
<fullTitle>Znai: Structure, Sub Headings [Flow]</fullTitle>
<text>
<text>Only a first level heading is treated as a first class citizen:Part of TOCSmallest unit of search result # First Class Citizen Nested sub headings only add visual distinction within a page. ## Sub heading content of sub heading ### Sub Sub heading content of sub sub heading content of sub headingcontent of sub sub heading</text>
<score>STANDARD</score>
</text>
</entry>
```
In the above XML, the text value of [this subheading](https://testingisdocumenting.org/znai/flow/structure#sub-heading) ("Sub heading") and [this subheading](https://testingisdocumenting.org/znai/flow/structure#sub-sub-heading) ("Sub Sub heading") are fully missing.

In the above snippet we see:
```
 ## Sub heading content of sub heading ### Sub Sub heading content of sub sub heading content of sub headingcontent of sub sub heading
```
Instead of I would expect to see:
```
## Sub heading content of sub heading ### Sub Sub heading content of sub sub heading Sub heading content of sub heading Sub Sub heading content of sub sub heading
```
