### ISSUE TITLE
:include-java-doc: defaults to inner class members instead of outer ones.

### ISSUE THREAD

**Issue by tianruig** [testingisdocumenting/znai#700]
Repro:

HelloWorld.java:
```
class HelloWorld {
   /** outer javadoc */
   int myVar;

   static class Inner {
      /** inner javadoc */
      int myVar;
   }
}
```

page.md:
```
:include-java-doc: HelloWorld.java {entry: "myVar"}
```

This renders as `inner javadoc`, whereas I would expect `outer javadoc` to be the default. Ideally, there would be a way to explicitly disambiguate which variable is being referred to.

**Comment by MykolaGolubyev** [comment]
Ah, that's not good.
gonna try to fix it ASAP and include in the next release
