### ISSUE TITLE
Top of image is being cut out

### ISSUE THREAD

**Issue by adzubla** [testingisdocumenting/znai#914]
I'm using some images with height of more than 2000 pixels. They are being scaled correcly to fit the page, but when I click on it (with the magnifing glass icon) to view it in its original size, the top of the image is being cut out.

An example image follows:

![fluxo_pagamento](https://user-images.githubusercontent.com/9607562/180093757-0c10cf08-8b3b-49f9-98c4-199411bee78b.png)

**Comment by MykolaGolubyev** [comment]
any chance you can try it with previous release? Want to check if this is a regression.

**Comment by adzubla** [comment]
I tested it with version 1.56 only. I will try with an older release tomorrow.

**Comment by MykolaGolubyev** [comment]
could you please also try it with the 1.58 just in case?

**Comment by adzubla** [comment]
I have tested with versions from 1.47 to 1.58 with the same behavior.

**Comment by adzubla** [comment]
Do you have an estimate of when the next version will come out?

**Comment by MykolaGolubyev** [comment]
Let me see if I can address a few more of your issues and cut a release. 
Also waiting on python auto ref support from last release - will chase there as well.

**Comment by MykolaGolubyev** [comment]
Btw, do you have a capacity to run/build from main branch to validate?

**Comment by adzubla** [comment]
I was able to test 1.59-SNAPSHOT just now and the image it seems to be working.

**Comment by MykolaGolubyev** [comment]
@adzubla Thank you for checking! I am trying to wrap up openapi3 support and then going to release
