### ISSUE TITLE
Embed swagger-ui

### ISSUE THREAD

**Issue by adzubla** [testingisdocumenting/znai#915]
Given a openapi yaml file, it would be nice to have a component to embed a swagger-ui inside a page.

**Comment by MykolaGolubyev** [comment]
In theory, you can use `:include-iframe:` 
Do you plan to use this to exercise a request? Or to document API?

**Comment by MykolaGolubyev** [comment]
@adzubla did you see [open-api](https://testingisdocumenting.org/znai/snippets/open-API) plugin?

**Comment by MykolaGolubyev** [comment]
is there any specific file that didn't work? going to try random selection
thanks for sharing

**Comment by MykolaGolubyev** [comment]
Tried https://raw.githubusercontent.com/OpenBanking-Brasil/areadesenvolvedor/master/documentation/source/swagger/swagger_admin_apis.yaml

<img width="973" alt="image" src="https://user-images.githubusercontent.com/11657860/181605587-c026d93d-d801-4148-a590-5692dbd28612.png">

**Comment by MykolaGolubyev** [comment]
after checking yaml file I can see a lot of missing data. My guess is open api v3 is quite different from v2. I am looking for the required changes

**Comment by MykolaGolubyev** [comment]
@adzubla any chance you can try version from the main branch?
temp plugin name is `include-open-api3`. plugin will be renamed to existing `open-api` before release.
