### ISSUE TITLE
Unforgiving json colorizer

### ISSUE THREAD

**Issue by adzubla** [testingisdocumenting/znai#916]
The "json colorizer" in version 1.58 causes an exception with bad formated json.
Its nice to have validation, but in some times is convenient to show just a json fragment in the documentation and the colorizer should do its best effort instead of raising an exception.

I'm using something like that:
```
{
  "request": { ... },
  "response": { ... }
}
```

**Comment by MykolaGolubyev** [comment]
Include-json plug-in requires a valid json as it does a bit more than syntax highlight.  Need to think if there is a good way to relax the rules. 

Did you try include-file plugin instead to display a json file?

alternatively you could include the valid json and then use json plugin parameters to collapse request and response by default

**Comment by adzubla** [comment]
I don't know if its feasible, but it would be good to have for each code block an option to (1) "best effort colorization, because its just a code fragment or pseudo code" and (2) "parse and validade code".

**Comment by MykolaGolubyev** [comment]
added doc section in #922
to show how to include incomplete json via `include-file` plugin
