### ISSUE TITLE
Undefined at the arrows at the end of a page

### ISSUE THREAD

**Issue by Haxiz** [testingisdocumenting/znai#956]
Just another small detail i found, which is actually present on the znai docs themselves.
At the end of every page there's arrows to move between pages. However, if the current page is either the landing page, the first page of a chapter or the last one, the word `undefined:` shows up on said arrows.

Examples:
![image](https://user-images.githubusercontent.com/31944205/185817848-5d8c78ef-5cca-4f33-9611-08a94ac7ff2e.png)

On the [Znai docs page](https://testingisdocumenting.org/znai/flow/structure)
![image](https://user-images.githubusercontent.com/31944205/185818302-a94be748-a7be-48f6-ab43-e82f6a2ea581.png)

This only happens on the border pages of a chapter, I assume its trying to show the name of the next or previous Chapter, but got lost in doing so

**Comment by MykolaGolubyev** [comment]
oh that looks like a regression. will add a fix and a e2e test tomorrow. 
thank you! 
may need to release a patch version

**Comment by MykolaGolubyev** [comment]
released https://testingisdocumenting.org/znai/release-notes/2022/#1591
