### ISSUE TITLE
Add title for left panel and attention signs

### ISSUE THREAD

**Issue by baobab-it** [testingisdocumenting/znai#959]
Sometime not all text can see in left side menu, can you add attribute title to show all text of topic?

About left panel. An example of a problem, in `Znai User Guide` open page "Getting Started" and in bottom sub panel "On-site Central Hub Deploym..." (text cutting and display `...`). It will be nice if I'm hovering the mouse on the link display title with full text description, like in a search box with title "hotkey /".

The same in attention signs if I use two sides pages more natural only show "note", "question", ... in title.

Or can add some option for attention signs, something like that:

```
Note:{title} Some text
```

If the option set - use title, otherwise - show label.

**Comment by MykolaGolubyev** [comment]
thanks for the suggestions.
could you please elaborate on this part
> The same in attention signs if I use two sides pages more natural only show "note", "question", ... in title.

**Comment by baobab-it** [comment]
Here are some images to explain what I mean.

Quiz (use attention signs and spoiler):

![](https://raw.githubusercontent.com/baobab-it/basics/main/img01.png)

![](https://raw.githubusercontent.com/baobab-it/basics/main/img02.png)

Screenshot of Micronaut documentation (only use title):

![](https://raw.githubusercontent.com/baobab-it/basics/main/img03.png)

**Comment by MykolaGolubyev** [comment]
Thanks for the visuals. I really like the overall approach of your quiz!
Need to think about some kind of options as the default behavior should be preserved. 

any chance you can share more info on what kind of docs you are working on in Discussion section? https://github.com/testingisdocumenting/znai/discussions/824

**Comment by baobab-it** [comment]
In issue above, I proposed use option {title}.

Without option `{title}`:

```
Question: What kind of programming language is Java?  -- Use current implementation
```

If I use option `{title}`:

```
Question:{title} What kind of programming language is Java?  -- Use my proposed implementation
```

**Comment by MykolaGolubyev** [comment]
does it mean when title is specified you expect to see an icon only?

**Comment by baobab-it** [comment]
Yes

**Comment by MykolaGolubyev** [comment]
I see. I like the direction of your though process. The concern I have is introducing a new syntax. 
Znai supports plugins and their formal parameters. In this case paragraph is text only.

I could introduce an `attention` fence block plugin like this

```attention-note {label: "optional text when is missing then icon only"}
markdown inside the whole block becomes the content of the sign
```

**Comment by baobab-it** [comment]
I like your idea. Always can change label on what you want or not use at all.

**Comment by MykolaGolubyev** [comment]
@baobab-it any chance you can try a local build and let me know your feedback?
