### ISSUE TITLE
Hiding/Showing depending on screen size

### ISSUE THREAD

**Issue by Haxiz** [testingisdocumenting/znai#985]
Hi there,
By any chance is there a way of hiding content based on the screen size? ie accessing a page from a phone vs a computer.
If not, what are the chances something like this could be added?

To elaborate a bit, certain things like images or text written `like this` tends to get cutoff on mobile screens, so having a way to hide elements on small screens to show a different version of them or something of the sorts.

Example: Open this page on both a phone and on a PC
https://www.mantaro.site/mantaro-wiki/

PC
![image](https://user-images.githubusercontent.com/31944205/188236721-26fffe17-e75d-4db1-b738-7b9544f39c97.png)

Phone
![image](https://user-images.githubusercontent.com/31944205/188236862-c200ffad-aa8b-4862-9788-a4f89078d57b.png)

**Comment by MykolaGolubyev** [comment]
Hello!
to clarify, is the ask to hide the image? When fit: true is not specified for an image, then it will be rendered as is and on mobile you will have to scroll left and right. 

Could you elaborate on “like this” example?

**Comment by Haxiz** [comment]
Sure,

currently i have `:include-image: assets/images/banner.jpg` for the image, adding {fit: true} to it makes it smaller to fit on pc, but on phone it stills needs to scroll left and right (it does make it smaller, but its barely noticeable).

My suggestion is to have an option like `{hide: {mobile:true, pc: false}}` that would hide an object (in this case an image) based on the screen size.

This would allow to use a large image on pc, and a smaller one on phone. This would avoid having to scroll the image, as it would be a different one altogether. As well as it would give more customization options.

Example:
```
:include-image: assets/images/banner.jpg {hide: {mobile: true, pc: false}}
:include-image: assets/images/emotes/m-sip.png {hide: {mobile: false, pc: true}}
```
It would show like so

![image](https://user-images.githubusercontent.com/31944205/188248429-e8e22908-a17e-468f-8af9-6f1f41409180.png)
![image](https://user-images.githubusercontent.com/31944205/188248443-334845cd-c5a0-4e12-ad9d-25f96c6b5248.png)

**Comment by MykolaGolubyev** [comment]
Wonderful suggestion! Wii need to figure it out the details.
