### ISSUE TITLE
Card component

### ISSUE THREAD

**Issue by Haxiz** [testingisdocumenting/znai#997]
I will be honest, I completely forgot we weren't in an issue before haha

Everything up to now:
![image](https://user-images.githubusercontent.com/31944205/189535938-49993c44-ad6f-45d0-9ecf-8e4b0a0b530c.png)
![image](https://user-images.githubusercontent.com/31944205/189535959-4f607a99-dc4d-4b8e-9995-040395493d26.png)
![image](https://user-images.githubusercontent.com/31944205/189535968-33c0ba9d-49a4-4990-a0d8-d644aaaceb89.png)
![image](https://user-images.githubusercontent.com/31944205/189535985-0d7a5ef5-4ed3-4486-ad64-1842319c155a.png)
![image](https://user-images.githubusercontent.com/31944205/189535993-9010b8cb-78dc-4bd3-822f-a387d1d64e40.png)

**Comment by MykolaGolubyev** [comment]
Thanks for copying all the context here.

**Comment by MykolaGolubyev** [comment]
@Haxiz all images seem to disappear. Any way to grab a few?

**Comment by Haxiz** [comment]
Ah the ones on the wiki? Yeah I need to fix those. Here's a few:

https://discordapp.com/assets/b5a892d37d598e0e73dce83212ad8512.svg
https://discordapp.com/assets/5a8d9af8b5b3922097b2cccfce844630.svg
https://discord.com/assets/141d49436743034a59dec6bd5618675d.svg
https://cdn.discordapp.com/emojis/553769632926924813.png
https://cdn.discordapp.com/emojis/787812272708780043.png

**Comment by MykolaGolubyev** [comment]
Can I copy the SVGs and use them inside znai documentation?

**Comment by Haxiz** [comment]
Go for it, they are mostly the emotes Discord uses

**Comment by MykolaGolubyev** [comment]
<img width="939" alt="Screen Shot 2022-09-11 at 5 39 13 PM" src="https://user-images.githubusercontent.com/11657860/189549953-cc216bbd-b316-49d7-881c-5ab837d3e9e6.png">

**Comment by MykolaGolubyev** [comment]
thinking to either use `height` instead of `imageHeight` or need to use `imageBackground`...

**Comment by MykolaGolubyev** [comment]
went with imageBackground

**Comment by Haxiz** [comment]
That looks so good! I love the backgrounds as well!

**Comment by MykolaGolubyev** [comment]
@Haxiz this was released
https://testingisdocumenting.org/znai/visuals/cards

**Comment by Haxiz** [comment]
Nice! New toy i'll definitely play with haha
Thank you so much!

**Comment by MykolaGolubyev** [comment]
Thanks for pushing it out of backlog! 
keep feedback coming, znai greatly benefits from it
